import 'dart:typed_data';

import 'package:sinapsis/features/transform/domain/clients/youtube_client.dart';
// Con prefijo: el paquete trae su propia `VideoUnavailableException`, que
// colisiona con la del dominio. El prefijo desambigua y, de paso, deja a la
// vista qué tipos vienen de afuera y cuáles son nuestros.
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt_api;

/// [YouTubeClient] sobre `youtube_explode_dart`.
///
/// El paquete no usa la API oficial de YouTube, y esa es justamente la razón
/// de elegirlo: no hace falta clave, no hay cuotas diarias y no hay una
/// consola de Google donde registrar el proyecto. Es lo que hace DownSub por
/// dentro, sin depender de que DownSub siga existiendo.
class YoutubeExplodeClient implements YouTubeClient {
  const YoutubeExplodeClient();

  @override
  Future<YouTubeVideoData> fetchVideo(
    String videoId, {
    List<String> preferredLanguages = const ['es', 'en'],
  }) async {
    final yt = yt_api.YoutubeExplode();

    try {
      final video = await yt.videos.get(videoId);
      final transcript = await _fetchTranscript(
        yt,
        videoId,
        preferredLanguages,
      );

      return YouTubeVideoData(
        title: video.title,
        authorName: video.author,
        authorChannelUrl: 'https://www.youtube.com/channel/${video.channelId}',
        publishedAt: video.publishDate ?? video.uploadDate,
        duration: video.duration,
        description: video.description,
        transcript: transcript,
      );
      // Un solo `catch` cubre los tres casos de "este video no está y no va
      // a estar": en el paquete, `VideoUnavailableException` (borrado o
      // privado) y `VideoRequiresPurchaseException` (de pago) extienden
      // `VideoUnplayableException`. Se traduce al tipo del dominio para que
      // quien llame no tenga que conocer las excepciones del paquete.
      //
      // Los fallos pasajeros —`TransientFailureException`,
      // `RequestLimitExceededException`— NO se atrapan acá a propósito: esos
      // sí valen la pena reintentarlos, y suben para que el elemento quede
      // marcado como fallido y se pueda volver a encolar.
    } on yt_api.VideoUnplayableException {
      throw VideoUnavailableException(videoId);
    } finally {
      // Cierra el cliente HTTP interno. Sin esto, cada video procesado deja
      // una conexión abierta y una cola larga las acumula todas.
      yt.close();
    }
  }

  @override
  Future<Uint8List> fetchAudio(String videoId) async {
    final yt = yt_api.YoutubeExplode();

    try {
      final manifest = await yt.videos.streams.getManifest(videoId);
      // La de mayor bitrate entre las que traen solo audio: no hace falta
      // el video para escuchar ni para transcribir, y bajar el archivo
      // completo pesaría muchas veces más para nada que se vaya a usar.
      final audioStream = manifest.audioOnly.withHighestBitrate();

      final chunks = <int>[];
      await for (final chunk in yt.videos.streams.get(audioStream)) {
        chunks.addAll(chunk);
      }
      return Uint8List.fromList(chunks);
    } on yt_api.VideoUnplayableException {
      throw VideoUnavailableException(videoId);
    } finally {
      yt.close();
    }
  }

  Future<List<TranscriptLine>> _fetchTranscript(
    yt_api.YoutubeExplode yt,
    String videoId,
    List<String> preferredLanguages,
  ) async {
    final manifest = await yt.videos.closedCaptions.getManifest(videoId);
    final chosen = _pickTrack(manifest, preferredLanguages);
    if (chosen == null) return const [];

    final track = await yt.videos.closedCaptions.get(chosen);

    return track.captions
        .map(
          (caption) =>
              TranscriptLine(offset: caption.offset, text: caption.text.trim()),
        )
        .where((line) => line.text.isNotEmpty)
        .toList();
  }

  /// Elige qué pista bajar.
  ///
  /// El orden de preferencia responde a qué sirve más:
  ///
  /// 1. Un idioma preferido, con subtítulos hechos por una persona.
  /// 2. Ese mismo idioma, autogenerados — peores, pero utilizables.
  /// 3. Cualquier pista que haya. Una transcripción en otro idioma sigue
  ///    siendo mejor que ninguna: se puede leer, buscar y traducir después.
  yt_api.ClosedCaptionTrackInfo? _pickTrack(
    yt_api.ClosedCaptionManifest manifest,
    List<String> preferredLanguages,
  ) {
    if (manifest.tracks.isEmpty) return null;

    for (final language in preferredLanguages) {
      final inLanguage = manifest.tracks.where(
        (track) => track.language.code.toLowerCase().startsWith(language),
      );
      if (inLanguage.isEmpty) continue;

      final human = inLanguage.where((track) => !track.isAutoGenerated);
      return human.isNotEmpty ? human.first : inLanguage.first;
    }

    final human = manifest.tracks.where((track) => !track.isAutoGenerated);
    return human.isNotEmpty ? human.first : manifest.tracks.first;
  }
}
